### ISSUE TITLE
Ввожу в нике пробелы и не могу звонить.

### ISSUE THREAD

**Issue by addep7y** [try2catch/ChatApp#13]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник из одних пробелов (4 достаточно)
3. Ввести ip собеседника (Коннектился к себе)

Ожидаемый результат:
Успешный коннект и общение, либо вместо такого ника ставить аннеймед

Фактический результат:
Залогинился с таким ником, и подключиться не могу (подключался к себе, бот лежит скорее всего). При нажатии на кнопку позвонить - 0 реакции.
Но вот с нормальным ником - нормально коннектит.

**Comment by try2catch** [comment]
Зачитано. Разберемся

Спасибо :)
