### ISSUE TITLE
Баг при дисконнекте во время ввода сообщения.

### ISSUE THREAD

**Issue by archy322** [try2catch/ChatApp#14]
Шаги по воспроизведению проблемы: 
1. Запустить программу.
2. Подключиться к себе.
3. Начать вводить сообщение.
4. Не отправив напечатанное сообщение в чат, нажать на Disconnct.
Ожидаемый результат:
Введенное сообщение удалится.
Фактический результат:
В поле ввода остается сообщение, с которым ничего нельзя сделать, пока снова не приконектишься.

![default](https://cloud.githubusercontent.com/assets/15378242/11781799/2eb9a4ce-a275-11e5-97ed-011ebade94c3.png)

**Comment by try2catch** [comment]
1) плохая идея коннектится к себе, это уже вызовет экспешенов кучу
2) это старая версия чата, уже была сдана новая, но здесь вряд ли будет висеть
    это я к тому, что в этой можно не искать баги. но если за найденное даже в этом 
    будут ставить баллы, то без проблем, можешь искать, ишьюзы закрывать не буду
