### ISSUE TITLE
Не возможно ввести Nick на русском языке.

### ISSUE THREAD

**Issue by DimaKovalchuk** [try2catch/ChatApp#15]
Шаги по воспроизведению проблемы:
1. Запустил программу
2. Ввожу ник на русском языке.

Ожидаемый результат:
Нормальное отображение ника на русском языке.

Фактический результат:
Прямоугольники в поле ввода ника на русском языке.

**Comment by try2catch** [comment]
русский язык отсутствует в принципе, потому как используется кодировка UTF-8. По протоколу от преподавателя.
