### ISSUE TITLE
Не могу начать работу с чатом

### ISSUE THREAD

**Issue by TkachenkoMax** [try2catch/ChatApp#2]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести что-либо в поле ника
3. Нажать соответствующую кнопку на форме или Enter на клавиатуре

Ожидаемый результат:
Присвоение ника, программа даст возможность к кому-то подключиться для общения

Фактический результат:
Ничего не происходит, либо не присваивается ник, либо он присваивается, но не разблокируется поле для ввода IP собеседника

PS: классная форма!

Update:
попробовал разные ники повводить, так вот работает похоже когда ник больше 3 знаков, если так и было задумано, то сорри, я об этом не знал)

**Comment by try2catch** [comment]
Да, ник должен быть больше 3 знаков и меньше 15
