### ISSUE TITLE
Бот Литвинова мне не отвечает

### ISSUE THREAD

**Issue by TkachenkoMax** [try2catch/ChatApp#3]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник, подтвердить
3. Подключиться к боту на files.litvinov.in.ua
4. Отправить сообщение

Ожидаемый результат:
Обратное сообщение в формате "Back: <мое сообщение>"

Фактический результат:
Сообщение не получено, другой чат получает

Update: подключился к себе, сообщения отправляются, но ответа также нет
![-1](https://cloud.githubusercontent.com/assets/15245651/11428810/72861ada-9478-11e5-9509-7778534558bc.jpg)

**Comment by try2catch** [comment]
Возможно, но маловероятно: проблема при общении с ботом, если он теперь работает с БД
Так как раньше с ботом можно было нормально переписываться
+ программа тестировалась с чатам других студентов: и входящие, и исходящие работали прекрасно

**Comment by TkachenkoMax** [comment]
Странно опять же, потому что скачал чаты двух других групп с потока - они могут общаться с ботом

**Comment by try2catch** [comment]
![image](https://cloud.githubusercontent.com/assets/14114513/11434337/9a4afdc8-94d3-11e5-91c4-8b49f4746884.png)

**Comment by TkachenkoMax** [comment]
Ок, никаких вопросов)
