### ISSUE TITLE
Не выводится сообщение о неработающем соединении.

### ISSUE THREAD

**Issue by addep7y** [try2catch/ChatApp#4]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Ввести ник
3. Ввести ip собеседника, который в оффлайне, либо любой другой ip.

Ожидаемый результат:
При не успешном соединении вывод оповещения по типу "could not connection" 

Фактический результат:
Программа зависает на короткое время, затем отвисает. Оповещения нет.

**Comment by try2catch** [comment]
Ничего нового. Все это написано в описании к релизу.
