### ISSUE TITLE
Не знаю баг это или нет но все же !

### ISSUE THREAD

**Issue by Sanches007** [try2catch/ChatApp#5]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Ввести ник, подтвердить
3. Подключиться к кому нибудь
4. Отправить сообщение

Ожидаемый результат:
возле сообщения отображение корректной даты и времени или хотя бы времени.

Фактический результат:
отображение даты, буквы "Т", времени и в конце 3 непонятные цифры

**Comment by try2catch** [comment]
Дата и время отображаются корректно, но не отформатированы. Для понимания того, что отображается советую ознакомится с классом LocalDateTime, и в частности, использованным методом now()
