### ISSUE TITLE
запуск 2х аккаунтов и больше.

### ISSUE THREAD

**Issue by Sanches007** [try2catch/ChatApp#6]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Ввести ник, подтвердить
3. Запустить еще раз программу
4. Ввести ник во 2 окне.

Ожидаемый результат:
нормальная работа программы

Фактический результат:
во 2 окне нельзя залогинится

**Comment by try2catch** [comment]
Это задание итерации 3. Пожалуйста, не нужно добавлять сюда то, что хочется лично вам. Чат выполнен по ТЗ данному Дмитрием Николаевичем, просьба по нему и проверять
