### ISSUE TITLE
Плохой фон

### ISSUE THREAD

**Issue by Sanches007** [try2catch/ChatApp#7]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Смотреть на рабочее окно

Ожидаемый результат:
нормальный понятный интерфейс

Фактический результат:
фон очень темный, плохо выделяются дествующие кнопки и почти не видно строки ввода сообщения.

**Comment by TkachenkoMax** [comment]
Надуманная проблема, IMO

**Comment by Sanches007** [comment]
Давай за своими действиями будешь следить.

**Comment by AlexeyButrim** [comment]
Sanches007,давай ты дерзить не будешь.

**Comment by try2catch** [comment]
1. Не баг
2. Кнопки "плохо видно" когда они отключены
