### ISSUE TITLE
Ввод русского ника.

### ISSUE THREAD

**Issue by Sanches007** [try2catch/ChatApp#8]
Шаги по воспроизведению проблемы:
1. Запустить программу
2. Вводить ник русскими буквами.

Ожидаемый результат:
нормальная работа программы

Фактический результат:
прямоугольные символы в место букв.

**Comment by TkachenkoMax** [comment]
Разработчики чата написали в релизе, что знают про эту проблему

**Comment by Sanches007** [comment]
У меня плохо с английским=))

**Comment by try2catch** [comment]
Да, кстати, все написано, стоило в транслейтор закинуть
