### ISSUE TITLE
Какая-либо реакция программы на оборванное интернет-соединение

### ISSUE THREAD

**Issue by TkachenkoMax** [try2catch/ChatApp#9]
Шаги по воспроизведению проблемы: 
1. Запустить программу
2. Провести все необходимые операции для начала диалога
3. В какой-то случайный момент принудительно оборвать интернет соединение (отключить wi-fi, выдернуть кабель из Ethernet порта)

Ожидаемый результат:
Какая-либо реакция от программы - уведомление или, возможно, закрытие программы

Фактический результат:

Ничего не происходить, создается впечатление что программа продолжает быть подключенной к собеседнику, сообщения "вроде как" отправляются (появляются на форме). Если отключиться и попытаться подключиться снова ничего не происходит, а ,наверное, было бы правильно вывести сообщение, что нет интернет-соединения

**Comment by try2catch** [comment]
Такс, начнем сначала.
1. Проблема все-таки скорее из раздела "желаемое", потому как чат очень типичен и далек от программы для масс и "обычных юзеров"
2. Идея проверки интернет соединения хорошая, в будущем попытаемся реализовать. Мысли, как это выполнить, есть. Спасибо
